---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: ensure docker is at the latest version
      yum: name=docker-ce state=latest
    - name: start docker
      service:
          name: docker
          state: started
