---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: ensure docker is at the latest version
      yum: name=docker-ce state=latest
    - name: start docker
      service:
          name: docker
          state: started
    - name: Install Pre-Reqs
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - epel-release
        - python-pip
    - name: Install virtualenv
      pip:
        name: virtualenv
        state: present
    - name: Install docker-py
      pip:
        name: docker-py
        state: present
    - name: Deploy NGINX
      docker_container:
        name: nginx
        image: nginx
        ports:
         - "80:80"
        state: started
        recreate: yes
